### ISSUE TITLE
Bug: Improve RefreshCache parameter documentation

### ISSUE THREAD

**Issue by agtenr** [dlw-digitalworkplace/dw-component-lib#46]
**Type**: Bug
**Package**: RefreshCache
**Details:** When using the refresh cache, it is not that clear that the time to live value should be in milliseconds. 
Maybe it would even be better to use seconds instead. Don't think you will ever want to cache something less then a second

**Comment by NickSevens** [comment]
Makes sense, but is quite breaking at this point, as some people are already using the library ... 😕 
_However_, since there's not a v1 released yet anyway, we could introduce it together with that 😄 
what do you think, @agtenr ?

**Comment by agtenr** [comment]
@NickSevens It will indeed be breaking. Agreed to do it in a v1 release
