### ISSUE TITLE
Feature: People Picker SharePoint provider

### ISSUE THREAD

**Issue by agtenr** [dlw-digitalworkplace/dw-component-lib#53]
### Type
 - [ ] Bug
 - [x] Improvement
 - [ ] Question

### Package
For which package do you whish to create this issue
 - [ ] React Reusable Components
 - [ ] Refresh Cache
 - [ ] Taxnonomy Provider
 - [ ] Utils
 - [x] Other: People Picker Provider

### Describe the bug
An implementation of a SharePoint provider for the people picker

The provider should replicate the OOTB people picker as much as possible:
- Retrieve data from 2 endpoints:
  - Graph /me/people
  - SP ApplicationPages people provider API

**Comment by NickSevens** [comment]
Especially important to be able to use _Everyone_ and _Everyone except externals_ accounts
