### ISSUE TITLE
Feature: PeoplePickerProvider Graph - Option for the /me/people end-point

### ISSUE THREAD

**Issue by agtenr** [dlw-digitalworkplace/dw-component-lib#59]
### Type
 - [ ] Bug
 - [x] Improvement
 - [ ] Question

### Package
For which package do you whish to create this issue
 - [ ] React Reusable Components
 - [ ] Refresh Cache
 - [ ] Taxnonomy Provider
 - [x] PeoplePicker Provider
 - [ ] Utils
 - [ ] Other:

### Component
Currently the Graph PeoplePicker provider uses the /users/$search endpoint. 
An extra option to the provider could be added to use the /me/people end-point.  This request gets the people most relevant to the signed-in user (/me), based on communication and collaboration patterns and business relationships.

**Comment by WTorremans** [comment]
Feature has been implemented and merged to master
