### ISSUE TITLE
Improvement: Bump React dependency version for compatibility with SPFx > 1.16.0

### ISSUE THREAD

**Issue by PieterVandendriessche** [dlw-digitalworkplace/dw-component-lib#76]
### Type
 - [ ] Bug
 - [X] Improvement
 - [ ] Question

### Package
For which package do you whish to create this issue
 - [X] React Reusable Components
 - [ ] Refresh Cache
 - [ ] Taxnonomy Provider
 - [ ] Utils
 - [ ] Other:

### Component
All components of DW React Controls

### Describe the bug
Bump the dependencies to have support for SPFx > 1.16.1

**Comment by PieterVandendriessche** [comment]
Currently stuck on tests that are failing, linked to update of React?

**Comment by NickSevens** [comment]
@PieterVandendriessche probably the reason, yes :) But, another question: why is this an issue to you exactly? SPFx 1.16.1 works perfectly with the packages as-is. (as we are using them for connect, for example)
I'm not opposed to updating of course :) but I'm not sure what the exact compatibility issue is?

**Comment by PieterVandendriessche** [comment]
Closed issue, using YARN will fix the issue. Project is compatible.
