### ISSUE TITLE
Children prop in components with newer versions of React

### ISSUE THREAD

**Issue by pierrenad** [dlw-digitalworkplace/dw-component-lib#79]
### Type
 - [x] Bug
 - [ ] Improvement
 - [ ] Question

### Package
For which package do you whish to create this issue
 - [x] React Reusable Components
 - [ ] Refresh Cache
 - [ ] Taxnonomy Provider
 - [ ] Utils
 - [ ] Other:

### Component
TreeView / TreeItem (maybe some other components too, didn't check all of them)

### Describe the bug
In the newer version of React, we now need to add the children prop to the components that handles children.
We need to go in the TreeView / TreeItem props to add " children?: ReactNode "

### To Reproduce
Use the TreeView with newer version of React.

**Comment by agtenr** [comment]
The Implicit children were removed from function components in react v18. 
https://solverfox.dev/writing/no-implicit-children/

2 options to fix:
 - Add the `children?: ReactNode` explicitly
 - Wrap the props with the React.PropsWithChildren Type
